In [75]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder ,LabelEncoder
import pickle

In [76]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [77]:
# Drop unnecessary columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [78]:
#Label Encoding Gender column
lable_encoder_gender = LabelEncoder()
data["Gender"] = lable_encoder_gender.fit_transform(data["Gender"])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
#One Hot Encoding Geography column
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [80]:
#Split the data into Dependent and Independent variables
X = data.drop('EstimatedSalary', axis=1)
Y = data['EstimatedSalary']

In [81]:
#Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [82]:
#Perform feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [83]:
#Save the scaler and encoders
with open('salaray_regression_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open('salary_regression_label_encoder.pkl', 'wb') as f:
    pickle.dump(lable_encoder_gender, f)
with open('salary_regression_onehot_encoder.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo, f)

In [84]:
#ANN Regression 
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [85]:
# Build the model and compile
model = Sequential(
     [
         Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
         Dense(32, activation='relu'),
         Dense(1)  # Output layer for regression
     ]
)
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

g:\Study_25\GEN_AI\Binary_Classification\Proj1\venv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [86]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [87]:
##Early Stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [88]:
#Train the model
history = model.fit(X_train, Y_train, validation_split=0.2, epochs=100, callbacks=[early_stopping, tensorboard_callback])

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 99991.5000 - mae: 99991.5000 - val_loss: 102079.6172 - val_mae: 102079.6172
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 99785.3594 - mae: 99785.3594 - val_loss: 101650.5625 - val_mae: 101650.5625
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 98999.5781 - mae: 98999.5781 - val_loss: 100461.2422 - val_mae: 100461.2422
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97309.6875 - mae: 97309.6875 - val_loss: 98252.8125 - val_mae: 98252.8125
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 94559.4531 - mae: 94559.4531 - val_loss: 94936.4062 - val_mae: 94936.4062
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 90733.3125 - mae: 90733.3125 - val_loss: 90544.6562 - val_mae: 90544.6562
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 85910.5078 - mae: 85910.5078 - val_loss: 85244.5312 - val_mae: 85244.5312
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80448.8672 - mae: 80448.8672 - val_loss: 79418.0312 - val_mae: 79418.0312
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 74697.3047 - mae: 74697.3047 - val_loss: 73490.4219 - val_mae: 73490.4219
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 69071.7266 - mae: 69071.7266 - val_loss: 67818.8828 - val_mae: 67818.8828
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63963.0547 - mae: 63963.0547 - val_loss: 62842.9531 - val_mae: 62842.9531
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 59691.2969 - mae: 59691.2969 - val_loss: 58692.3281 - val_mae: 58692.3281
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56371.5664 - mae: 56371.5664 - val_loss: 55555.1016 - val_mae: 55555.1016
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53982.8633 - mae: 53982.8633 - val_loss: 53320.9844 - val_mae: 53320.9844
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 52420.4648 - mae: 52420.4648 - val_loss: 51923.8164 - val_mae: 51923.8164
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 51497.9609 - mae: 51497.9609 - val_loss: 51058.8398 - val_mae: 51058.8398
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50950.0117 - mae: 50950.0117 - val_loss: 50563.1250 - val_mae: 50563.1250
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50664.3008 - mae: 50664.3008 - val_loss: 50340.2500 - val_mae: 50340.2500
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50514.6445 - mae: 50514.6445 - val_loss: 50198.7344 - val_mae: 50198.7344
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50429.1484 - mae: 50429.1484 - val_loss: 50123.1758 - val_mae: 50123.1758
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50366.8516 - mae: 50366.8516 - val_loss: 50061.1953 - val_mae: 50061.1953
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50316.3164 - mae: 50316.3164 - val_loss: 50018.0703 - val_mae: 50018.0703
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50277.1719 - mae: 50277.1719 - val_loss: 49983.9414 - val_mae: 49983.9414
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50243.5156 - mae: 50243.5156 - val_loss: 49958.5859 - val_mae: 49958.5859
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50211.5664 - mae: 50211.5664 - val_loss: 49932.1953 - val_mae: 49932.1953
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50184.8086 - mae: 50184.8086 - val_loss: 49915.6914 - val_mae: 49915.6914
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50153.3359 - mae: 50153.3359 - val_loss: 49897.6133 - val_mae: 49897.6133
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50125.3203 - mae: 50125.3203 - val_loss: 49880.0859 - val_mae: 49880.0859
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50100.4766 - mae: 50100.4766 - val_loss: 49856.5664 - val_mae: 49856.5664
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50079.2344 - mae: 50079.2344 - val_loss: 49840.6797 - val_mae: 49840.6797
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50057.2148 - mae: 50057.2148 - val_loss: 49837.4141 - val_mae: 49837.4141
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50037.4883 - mae: 50037.4883 - val_loss: 49822.5742 - val_mae: 49822.5742
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50017.4688 - mae: 50017.4688 - val_loss: 49816.3516 - val_mae: 49816.3516
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49994.6445 - mae: 49994.6445 - val_loss: 49796.2734 - val_mae: 49796.2734
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49974.6445 - mae: 49974.6445 - val_loss: 49787.5938 - val_mae: 49787.5938
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49954.5703 - mae: 49954.5703 - val_loss: 49777.5898 - val_mae: 49777.5898
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49937.3594 - mae: 49937.3594 - val_loss: 49762.5469 - val_mae: 49762.5469
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49922.3047 - mae: 49922.3047 - val_loss: 49752.3555 - val_mae: 49752.3555
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49903.1719 - mae: 49903.1719 - val_loss: 49739.7656 - val_mae: 49739.7656
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49890.8047 - mae: 49890.8047 - val_loss: 49724.8281 - val_mae: 49724.8281
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49873.5469 - mae: 49873.5469 - val_loss: 49721.9492 - val_mae: 49721.9492
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49861.4258 - mae: 49861.4258 - val_loss: 49713.1367 - val_mae: 49713.1367
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49846.4219 - mae: 49846.4219 - val_loss: 49702.0469 - val_mae: 49702.0469
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49834.3359 - mae: 49834.3359 - val_loss: 49694.9961 - val_mae: 49694.9961
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49824.9492 - mae: 49824.9492 - val_loss: 49679.7305 - val_mae: 49679.7305
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49810.4648 - mae: 49810.4648 - val_loss: 49677.0039 - val_mae: 49677.0039
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49797.0117 - mae: 49797.0117 - val_loss: 49668.0781 - val_mae: 49668.0781
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49782.8867 - mae: 49782.8867 - val_loss: 49656.1094 - val_mae: 49656.1094
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49773.4844 - mae: 49773.4844 - val_loss: 49654.1133 - val_mae: 49654.1133
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49762.0195 - mae: 49762.0195 - val_loss: 49647.6758 - val_mae: 49647.6758
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49752.4961 - mae: 49752.4961 - val_loss: 49637.7461 - val_mae: 49637.7461
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49744.3867 - mae: 49744.3867 - val_loss: 49632.3594 - val_mae: 49632.3594
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49733.5586 - mae: 49733.5586 - val_loss: 49630.9414 - val_mae: 49630.9414
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49719.3203 - mae: 49719.3203 - val_loss: 49631.2617 - val_mae: 49631.2617
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49713.3594 - mae: 49713.3594 - val_loss: 49633.8945 - val_mae: 49633.8945
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49700.7852 - mae: 49700.7852 - val_loss: 49619.9844 - val_mae: 49619.9844
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49693.4492 - mae: 49693.4492 - val_loss: 49619.4102 - val_mae: 49619.4102
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49682.6016 - mae: 49682.6016 - val_loss: 49612.6758 - val_mae: 49612.6758
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49676.1406 - mae: 49676.1406 - val_loss: 49602.2500 - val_mae: 49602.2500
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49669.1836 - mae: 49669.1836 - val_loss: 49589.9141 - val_mae: 49589.9141
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49660.5703 - mae: 49660.5703 - val_loss: 49587.8438 - val_mae: 49587.8438
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49653.7969 - mae: 49653.7969 - val_loss: 49581.1094 - val_mae: 49581.1094
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49646.5039 - mae: 49646.5039 - val_loss: 49575.7344 - val_mae: 49575.7344
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49638.4258 - mae: 49638.4258 - val_loss: 49575.4805 - val_mae: 49575.4805
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49629.2539 - mae: 49629.2539 - val_loss: 49573.5781 - val_mae: 49573.5781
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49622.1758 - mae: 49622.1758 - val_loss: 49570.0781 - val_mae: 49570.0781
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49615.2383 - mae: 49615.2383 - val_loss: 49564.0234 - val_mae: 49564.0234
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49607.4648 - mae: 49607.4648 - val_loss: 49558.9492 - val_mae: 49558.9492
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49601.0859 - mae: 49601.0859 - val_loss: 49557.7305 - val_mae: 49557.7305
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49594.8594 - mae: 49594.8594 - val_loss: 49558.0508 - val_mae: 49558.0508
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49589.0938 - mae: 49589.0938 - val_loss: 49548.8516 - val_mae: 49548.8516
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49581.0898 - mae: 49581.0898 - val_loss: 49550.1367 - val_mae: 49550.1367
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49572.3633 - mae: 49572.3633 - val_loss: 49551.2344 - val_mae: 49551.2344
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49570.6250 - mae: 49570.6250 - val_loss: 49547.7383 - val_mae: 49547.7383
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49562.6641 - mae: 49562.6641 - val_loss: 49547.3086 - val_mae: 49547.3086
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49554.7617 - mae: 49554.7617 - val_loss: 49541.7188 - val_mae: 49541.7188
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49549.4844 - mae: 49549.4844 - val_loss: 49539.7539 - val_mae: 49539.7539
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49543.9609 - mae: 49543.9609 - val_loss: 49539.1250 - val_mae: 49539.1250
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49538.4609 - mae: 49538.4609 - val_loss: 49541.5195 - val_mae: 49541.5195
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49532.2969 - mae: 49532.2969 - val_loss: 49542.2891 - val_mae: 49542.2891
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49527.8281 - mae: 49527.8281 - val_loss: 49543.4688 - val_mae: 49543.4688
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49519.9844 - mae: 49519.9844 - val_loss: 49541.0352 - val_mae: 49541.0352
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49515.3750 - mae: 49515.3750 - val_loss: 49538.5039 - val_mae: 49538.5039
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49509.0547 - mae: 49509.0547 - val_loss: 49536.0508 - val_mae: 49536.0508
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49505.8945 - mae: 49505.8945 - val_loss: 49539.3164 - val_mae: 49539.3164
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49503.6914 - mae: 49503.6914 - val_loss: 49535.2109 - val_mae: 49535.2109
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49493.1367 - mae: 49493.1367 - val_loss: 49534.3086 - val_mae: 49534.3086
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49490.6914 - mae: 49490.6914 - val_loss: 49532.6641 - val_mae: 49532.6641
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49487.3789 - mae: 49487.3789 - val_loss: 49538.5234 - val_mae: 49538.5234
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49483.1914 - mae: 49483.1914 - val_loss: 49540.0664 - val_mae: 49540.0664
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49476.3867 - mae: 49476.3867 - val_loss: 49535.7969 - val_mae: 49535.7969
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49473.4414 - mae: 49473.4414 - val_loss: 49533.8711 - val_mae: 49533.8711
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49471.4336 - mae: 49471.4336 - val_loss: 49534.9297 - val_mae: 49534.9297
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49463.7617 - mae: 49463.7617 - val_loss: 49532.6719 - val_mae: 49532.6719
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49459.9062 - mae: 49459.9062 - val_loss: 49533.6484 - val_mae: 49533.6484
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49455.7188 - mae: 49455.7188 - val_loss: 49537.1367 - val_mae: 49537.1367
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49452.4062 - mae: 49452.4062 - val_loss: 49535.1758 - val_mae: 49535.1758
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49446.8789 - mae: 49446.8789 - val_loss: 49530.1719 - val_mae: 49530.1719
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49444.0547 - mae: 49444.0547 - val_loss: 49531.9414 - val_mae: 49531.9414
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49443.1094 - mae: 49443.1094 - val_loss: 49532.8203 - val_mae: 49532.8203

In [89]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [90]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [91]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 12504), started 1:17:06 ago. (Use '!kill 12504' to kill it.)